### ISSUE TITLE
@rendition should be allowed on <list>

### ISSUE THREAD

**Issue by rvdb** [OpenEdition/tei.openedition#4]
There's an inconsistency between the documentation and the OpenEdition schema, concerning the encoding of lists.

While the [documentation](https://github.com/OpenEdition/tei.openedition/wiki/Creating-a-TEI-document-in-Lodel-1.0#list-style-types) specifies how different list style types can be specified using the `//list/@rendition` attribute, the [ODD file (l.1913)](https://github.com/OpenEdition/tei.openedition/blob/master/odd/tei.openedition.odd#L1913) deletes the `@rendition` attribute from the `<list>` element.

Moreover, though not schema-related, while the `//list/@rendition` attribute is correctly transformed to a `//(ul|ol)//@style` attribute in the HTML generated by Lodel, its list-style-type property is always overridden by these CSS rules in the [screen.css](https://jtei.revues.org/css/screen.css) stylesheet:

    /* listes */
    div.text ul > li ,#abstract ul > li {list-style-type:square}
    div.text ol > li ,#abstract ol > li {list-style-type:decimal}

Consequently, the list styles discussed in the documentation will never be honoured in the output HTML.

**Comment by jfriviere** [comment]
You're right for both points.
The odd (and schema) issue is fixed in release 1.5.2 https://github.com/OpenEdition/tei.openedition/releases/tag/1.5.2 
Persistant URL : http://lodel.org/ns/tei.openedition.1.5.2/tei.openedition.1.5.2.xsd

The css issue on JTEI is specific to this site template. 
It is now fixed. So the list display should now honour the TEI.

**Comment by rvdb** [comment]
Perfect, thanks! I confirm it is working as documented, now.
